name: Send Shift Reminders

on:
  schedule:
    - cron: '0 20 * * *' # cada 10 minutos para test
  workflow_dispatch: # permite lanzarlo a mano

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      - name: Run reminder script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: npm run cron:send-reminders
        working-directory: ./api
